---
##########################
# versions

openstack_version: ussuri

kolla_manager_version: latest
osism_manager_version: latest

##########################
# manager

ceph_ansible_enable: false

configure_cockpit: true
cockpit_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

ara_enable: true
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

netbox_enable: no
