cloud_provider            = "citycloud"
availability_zone         = "nova"
network_availability_zone = "nova"
flavor_manager            = "8C-32GB-150GB"
image                     = "Ubuntu 20.04 Focal Fossa 20200423"
public                    = "ext-net"
