---
- name: Apply role configuration
  hosts: testbed-iam-manager.osism.local
  connection: local
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    configuration_git_host: github.com
    configuration_git_port: 443
    configuration_git_repository: SovereignCloudStack/testbed-iam.git
    configuration_git_protocol: https

  roles:
    - ansible-configuration
