---
name: Daily deployment (betacloud)

on:
  push:
    paths:
      - '.github/workflows/deploy-daily-betacloud.yml'
    branches:
      - master
  schedule:
    - cron: '0 4 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version:
          - 0.13.4

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Prepare use of openstack
        shell: bash
        working-directory: ./terraform
        env:
          OPENSTACK: ${{ secrets.OPENSTACK }}
        run: |
          echo "$OPENSTACK" > clouds.yaml
      - name: Prepare use of minio
        shell: bash
        working-directory: ./terraform
        env:
          MINIO: ${{ secrets.MINIO }}
        run: |
          echo "$MINIO" > minio.env
          cp minio.tf.disabled minio.tf
      - name: Initialization
        run: make init
        working-directory: ./terraform
      - name: Detach floating ip address
        run: make detach || exit 0
        working-directory: ./terraform
        env:
          FLOATING_IP_ADDRESS: ${{ secrets.FLOATING_IP_ADDRESS }}
      - name: Remove existing environment
        run: make clean|| exit 0
        working-directory: ./terraform

  deploy:
    needs: cleanup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version:
          - 0.13.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Prepare use of openstack
        shell: bash
        working-directory: ./terraform
        env:
          OPENSTACK: ${{ secrets.OPENSTACK }}
        run: |
          echo "$OPENSTACK" > clouds.yaml
      - name: Prepare use of minio
        shell: bash
        working-directory: ./terraform
        env:
          MINIO: ${{ secrets.MINIO }}
        run: |
          echo "$MINIO" > minio.env
          cp minio.tf.disabled minio.tf
      - name: Initialization
        run: make init
        working-directory: ./terraform
      - name: Attach floating ip address
        run: make attach PARAMS=$FLOATING_IP_ADDRESS
        working-directory: ./terraform
        env:
          FLOATING_IP_ADDRESS: ${{ secrets.FLOATING_IP_ADDRESS }}
      - name: Deploy environment
        run: make deploy PARAMS="-var endpoint=$ENDPOINT"
        working-directory: ./terraform
        env:
          ENDPOINT: ${{ secrets.ENDPOINT }}
