---
name: Check python syntax

on:
  push:
    paths:
      - '.github/workflows/syntax-python.yml'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/syntax-python.yml'
      - '**.py'

jobs:
  default:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip3 install flake8
      - run: flake8
